# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 10 # it will paginate after this number
paginate_path: "/blog/page:num/"
language: 'en-uk'

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
url: "https://infoseciitr.github.io/" #Value gets overwritten at time of deployment by jekyll in CNAME file used
baseurl: "/l33t/../" # This value is replaced to empty string by github if set to '/'

# Website info
title: InfosecIITR
description: The official website of InfosecIITR
# cover: /assets/images/infosec.jpeg
logo: /assets/images/infosec.jpeg
logo_dark: /assets/images/small-logo.jpg
favicon: /assets/images/small-logo.jpg
production_url: https://jekyller.github.io/jasper2/
source_url: https://github.com/jekyller/jasper2/

# Social info
navigation: True # show the navbar links
subscribers: False # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: infoseciitr # replace by your username
facebook: InfoSecIITR # replace by your username

# Disqus
disqus: False
disqus_shortname:  # replace with your disqus username

# Google Analytics
google_analytics: # replace with your GA tracking identifier

# Permalinks
# permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins: [jekyll-paginate, jekyll-feed, jekyll-sitemap]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
# safe: False
# lsi: False
# username: jekyller
# repo: jasper2
# branch: master
# relative_source: ../jasper2/
# destination: ../jasper2-pages/
# production_url:  https://jekyller.github.io/jasper2/
# source_url:  https://github.com/jekyller/jasper2/

# exclude:
#   - assets/css
#   - node_modules
#   - vendor
#   - .travis.yml
#   - Gemfile
#   - Gemfile.lock
#   - GHOST.txt
#   - gulpfile.js
#   - LICENSE
#   - package.json
#   - Rakefile
#   - README.md
#   - script.py
#   - changelog.md
#   - "*.Rmd"
#   - .git*
